name: Python CI   #name :Workflow name; in github actions we need to specify data in key value pair

# Trigger the workflow on any push to the main branch or pull request
on:                         # on : here we define Event that will trigger a workflow
  push:                     # Event1 name : Push : trigger the workflow if there is push in main branch
    branches:
      - main
  pull_request:              # Event 2 Name : pull_request : trigger the workflow if there is pull request on main brnach
    branches:                  # Series of Events are in "OR" logic. So trigger the workflow if Event 1 or Event2 occurs
      - main

jobs:            # We can have multiple jobs and we can name them and runs in containers
  test:
    runs-on: ubuntu-latest     # this job is running on ubuntu-latest container by github

    steps:
      # Step 1: Check out the code from the repository
      - name: Check out code
        uses: actions/checkout@v2        # predefined action from github actions

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run tests
      - name: Run tests
        run: pytest
